# Modified from example project here: https://github.com/kbx81/esphome-configs
substitutions:
  <<: !include secrets.yaml

esphome:
  name: ${node_name}
  build_path: ../build/${node_name}

wifi:
  ssid: ${wifi_ssid}
  password: ${wifi_password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${node_name}
    password: ${ap_password}

# captive_portal:

ota:
  password: ${ota_password}

# Enable logging
logger:

# Enable Home Assistant API and define services
api:
  encryption:
    key: ${api_key}
  password: ${api_password}
  reboot_timeout: 120min

preferences:
  flash_write_interval: 2min

button:
  - platform: restart
    name: ${node_friendly_name} Restart

sensor:
  - platform: wifi_signal
    name: ${node_friendly_name} Wi-Fi Signal
    update_interval: 15s
